import fs from 'fs';
import path from 'path';
import https from 'https';

const METRICS_FILE = path.resolve('data/SERVER_METRICS.md');

// We use mcsrvstat.us public API to fetch the server health without needing mineflayer to join
// Defaulting to a placeholder if environment variable is not set in GitHub Secrets
const serverIp = process.env.MC_SERVER_HOST || "play.myserver.com";
const serverPort = process.env.MC_SERVER_PORT || "25565";

const apiUrl = `https://api.mcsrvstat.us/3/${serverIp}:${serverPort}`;

console.log(`Fetching metrics for ${serverIp}:${serverPort}...`);

https.get(apiUrl, (res) => {
  let data = '';

  res.on('data', (chunk) => {
    data += chunk;
  });

  res.on('end', () => {
    try {
      const status = JSON.parse(data);
      const timestamp = new Date().toUTCString();
      
      let markdown = `# Server Metrics Log\n\n`;
      markdown += `> This file is auto-generated by GitHub Actions to track real server health and activity over time.\n\n`;
      
      markdown += `## Latest Check: ${timestamp}\n\n`;
      
      if (status.online) {
        markdown += `- **Status**: 🟢 Online\n`;
        markdown += `- **Players**: ${status.players?.online || 0} / ${status.players?.max || 0}\n`;
        markdown += `- **Version**: ${status.version || 'Unknown'}\n`;
        markdown += `- **Software**: ${status.software || 'Vanilla'}\n`;
        markdown += `- **Ping**: ${status.ping || 0}ms\n`;
        
        if (status.motd && status.motd.clean) {
          markdown += `\n**MOTD**:\n\`\`\`text\n${status.motd.clean.join('\n')}\n\`\`\`\n`;
        }
      } else {
        markdown += `- **Status**: 🔴 Offline\n`;
        markdown += `- The server is currently offline or sleeping (Aternos).\n`;
      }

      markdown += `\n---\n*Metrics collected via mcsrvstat.us API*\n`;

      fs.writeFileSync(METRICS_FILE, markdown, 'utf8');
      console.log(`Successfully updated ${METRICS_FILE}`);
      
    } catch (e) {
      console.error('Failed to parse API response:', e.message);
      process.exit(1);
    }
  });
}).on('error', (err) => {
  console.error('Error fetching metrics:', err.message);
  process.exit(1);
});
